language: python
python:
  - 2.7

install:
  - python bootstrap.py
  - bin/buildout

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bin/nosetests
  - bin/mrbob -O collective.foo --config test_answers.ini ./bobtemplates/plone
  - cd collective.foo
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
  - bin/test

notifications:
  irc:
    - "irc.freenode.org#digipub"

language: python
