language: python
python:
  - 2.7

install:
  - python bootstrap.py
  - bin/buildout

script:
  - bin/nosetests
  - bin/mrbob -O collective.foo --config test_answers.ini ./bobtemplates/plone
  - cd collective.foo
  - make

notifications:
  irc:
    - "irc.freenode.org#digipub"
